services:
  task_management-db:
    restart: unless-stopped
    image: postgres:14
    env_file:
      - .env
    volumes:
      - task_management-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - task_management_network

  task_management_backend:
    restart: unless-stopped
    container_name: task_management_backend
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "9005:8000"
    env_file:
      - .env
    networks:
      - task_management_network
    depends_on:
      task_management-db:
        condition: service_healthy
networks:
  task_management_network:
volumes:
  task_management-db-data:

