# Generated by Django 5.1.7 on 2025-03-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='planed_kpi',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
